### ISSUE TITLE
Unknown plugin "transform-runtime"

### ISSUE THREAD

**Issue by rgfretes** [Macil/redux-action-log#5]
When used in a project it cannot build it since it is missing the "transform-runtime" plug in in the dependencies: 

Loading dependency graph, done.
error: bundling failed: ReferenceError: Unknown plugin "transform-runtime" specified in "{PorjectFolder}/node_modules/redux-action-log/.babelrc" at 0, attempted to resolve relative to "{PorjectFolder}/node_modules/redux-action-log"

**Comment by Macil** [comment]
This error is happening because Babel is being run on redux-action-log. Like many modules, redux-action-log is published on npm pre-compiled by Babel, so Babel shouldn't be run on it again. If you're using webpack, you should configure babel-loader to exclude the node_modules directory (as suggested [in babel-loader's docs](https://github.com/babel/babel-loader/tree/7.x#usage)).
